import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { GoogleOAuthProvider } from "@react-oauth/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="en">
        <body className={inter.className}>
        <GoogleOAuthProvider clientId="613877575592-fu7u9afip45pkmhenm9l4r1kk2gohvg4.apps.googleusercontent.com" >
          {children}
        </GoogleOAuthProvider>

        </body>
    </html>

  );
}
